### ISSUE TITLE
Watcher's behavior in go-zookeeper

### ISSUE THREAD

**Issue by elakito** [samuel/go-zookeeper#135]
I am not sure if I understand  go-zookeeper watcher's behavior in contrast to that of Java's implementation and have the following question.

Java Zookeepr's watcher API uses a one-time callback that is invoked when the event occurs. So, one can reactivate the watch synchronously when the callback is invoked. In that way, the watch can stay at the node.

In contrast, go-zookeeper uses a one-time channel where the event is sent. And, in order to continuously receive events, one will need to re-watch the node (i.e., call appropriate *W method). However, this may happen after the previous watcher has been deleted and can that lead to some events to be lost?

Or am I missing something here?

Thanks for your help.
regards, aki

**Comment by danielkrainas** [comment]
From [Zookeeper's Docs](https://zookeeper.apache.org/doc/r3.1.2/zookeeperProgrammers.html#sc_WatchGuarantees):

### Things to Remember about Watches
- Because watches are one time triggers and there is latency between getting the event and sending a new request to get a watch you cannot reliably see every change that happens to a node in ZooKeeper. **Be prepared to handle the case where the znode changes multiple times between getting the event and setting the watch again. (You may not care, but at least realize it may happen.)**

**Comment by elakito** [comment]
@danielkrainas thanks for the info.
I didn't realize zookeeper's watch can also miss some changes (I had thought we could avoid this situation in zookeeper when you reactivated the watch while processing a change event during the same synchronous invocation).

**Comment by MeninaChimp** [comment]
It may be better to set up a switch that allows users to decide whether to use a one-time watch or a continuous watch
