### ISSUE TITLE
bug in function handler

### ISSUE THREAD

**Issue by beardeddog** [samuel/go-zookeeper#5]
encountered a repeated failure traced down into `conn.go`, function `handler`, in the `receive loop` where the the `log` message `Response for unknown request with xid #` is sent.

existing code is

``` go
} else {
            c.requestsLock.Lock()
            req, ok := c.requests[res.Xid]
            if ok {
                delete(c.requests, res.Xid)
            }
            c.requestsLock.Unlock()

            if !ok {
>>              log.Printf("Response for unknown request with xid %d", res.Xid)
            } else {
                _, err := decodePacket(buf[:blen], req.recvStruct)
                req.recvChan <- err
            }
        }
```

changed the 

``` go
log.Printf("Response for unknown request with xid %d", res.Xid)
```

to be

``` go
req.recvChan <- errors.New("UNKWNREQ: Response for unknown request with xid " + string(res.Xid))
```

basically the channel needs a reply, otherwise we just hang 

the error message I'm sending back is something you probably want to align with your error handling, but I did need to see this specific error so I could attempt recovery in my client code, in my case I just retry if I get this error

Bill

**Comment by horkhe** [comment]
We experienced the same issue and I have traced down the root cause. When requests are generated from different goroutines several requests may be assigned the same `xid` due to the fact that `conn.lastZxid` is not updated right after a request is created, but after a response is received. I am going to submit a pull request to fix that.
