### ISSUE TITLE
removing/disabling logging

### ISSUE THREAD

**Issue by theckman** [samuel/go-zookeeper#60]
I wanted to open an issue for this issue to get feedback before going further and starting to modify the code in preparation for a PR.

When using the library, it log failures and the like by default:

```
2015/06/04 21:07:54 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connection refused
```

Without setting the writer for all logging to something that isn't stdout, there doesn't appear to be a way to disable this logging. Is there a reason logging was enabled in the library by default?

**Comment by theckman** [comment]
Nevermind, I'm totally a tool.

**Comment by samuel** [comment]
I believe there's 3 instance of logging in the server: failed to connect to server, failed to set previous watches, and a catch all for unexpected errors (which likely point to bigger issues).

One alternative is to turn off logging and use exported metrics so that any existing alerting infrastructure can be used (e.g. failed to connect N times in M seconds).. this likely should be added anyway regardless of logging.

Do you think it would be ok if you could pass in a custom logger to the client (`func (c *Conn) SetLogger(Logger)`) conforming to an interface like:

```
type Logger interface {
    Printf(format string, v ...interface{})
}
```

and by default the stdlib `log` would be used. Then could override it to disable logging entirely or reroute to a more appropriate place (perhaps syslog if using it).

**Comment by theckman** [comment]
I think that would make sense to me. Then have an unexported struct field for the Logger. To avoid breaking the old way, we could default to setting up a logger that has the same behavior as now.
